---
# vars file for nextepc
packages:
  centos:
      - mongodb-org
      - iproute
      - git
      - flex
      - bison
      - autoconf
      - libtool
      - lksctp-tools-devel
      - libidn-devel
      - gnutls-devel
      - libgcrypt-devel
      - openssl-devel
      - cyrus-sasl-devel
      - libyaml-devel
      - epel-release
  fedora:
      - mongodb-server
      - udev
      - iproute
      - git
      - gcc
      - flex
      - bison
      - autoconf
      - libtool
      - mongo-c-driver-devel
      - lksctp-tools-devel
      - libidn-devel
      - gnutls-devel
      - libgcrypt-devel
      - openssl-devel
      - cyrus-sasl-devel
      - snappy-devel
      - libyaml-devel
  freeBSD:
      - mongodb
      - git
      - gcc
      - bison
      - gsed
      - pkgconf
      - autoconf
      - automake
      - libtool
      - mongo-c-driver
      - gnutls
      - libgcrypt
      - libidn
      - libyaml
  mac:
      - mongodb
      - autoconf
      - automake
      - libtool
      - gnu-sed
      - mongo-c-driver
      - libusrsctp
      - gnutls
      - libgcrypt
      - libidn
      - libyaml
      - pkg-config
  ubuntu:
      - mongodb
      - udev
      - net-tools
      - autoconf
      - libtool
      - gcc
      - pkg-config
      - git
      - flex
      - bison
      - libsctp-dev
      - libgnutls28-dev
      - libgcrypt-dev
      - libssl-dev
      - libidn11-dev
      - libmongoc-dev
      - libbson-dev
      - libyaml-dev
  ubuntu_trusty:
      - mongodb
      - udev
      - git
      - gcc
      - flex
      - bison
      - make
      - autoconf
      - libtool
      - pkg-config
      - libsctp-dev
      - libssl-dev
      - libgnutls-dev
      - libidn11-dev
      - libyaml-dev
      - g++

