- name: install "{{ packages.freeBSD }}"
  become: true
  pkgng:
    name: "{{ packages.freeBSD }}"
    state: latest

- name: Start MongoDb
  become: true
  shell:
    cmd: |
      mkdir -p data/db
      mongod --dbpath data/db
  args:
    warn: false

- name: Setup network
  become: true
  shell:
    cmd: |
      ifconfig lo0 alias 127.0.0.2 netmask 255.255.255.255
      ifconfig lo0 alias 127.0.0.3 netmask 255.255.255.255
      ifconfig lo0 alias 127.0.0.4 netmask 255.255.255.255
      ifconfig lo0 alias 127.0.0.5 netmask 255.255.255.255
  args:
    warn: false

- name: Enable IP forwarding
  become: true
  shell:
    cmd: |
      sysctl -w net.inet.ip.forwarding=1
  args:
    warn: false

- name: Compile nextEPC
  become_user: nobody
  shell: |
    mkdir ~/acetcom
    cd ~/acetcom
    git clone https://github.com/acetcom/nextepc 
    cd nextepc
    autoreconf -iv
    ./configure --prefix=`pwd`/install
    make -j `nproc`
    make install
  args:
    warn: false