- name: Include Ubuntu trusty yaml
  include_tasks: ubuntu_trusty.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty" and ansible_distribution_version <= '14.04'

- name: Include Ubuntu yaml
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "trusty"

- name: Include CentOS yaml
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Include Fedora yaml
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Include FreeBSD yaml
  include_tasks: freeBSD.yml
  when: ansible_distribution == "FreeBSD"

- name: Include MacOS yaml
  include_tasks: mac.yml
  when: ansible_distribution == "MacOSX"